### ISSUE TITLE
Make binary release

### ISSUE THREAD

**Issue by johanhaleby** [levyfan/guava-cache-redis#1]
It would be great if you could create a binary release of this project and publish to maven central

**Comment by levyfan** [comment]
OK. I open a ticket on https://issues.sonatype.org/browse/OSSRH-24621

**Comment by levyfan** [comment]
please use

```
<dependency>
    <groupId>com.github.levyfan</groupId>
    <artifactId>guava-cache-redis</artifactId>
    <version>0.0.2</version>
</dependency>
```
